"""
model_backend.py
HairBright MMM — model loading and inference functions.

Generated by notebook 10 on 20260420.
Bundle: mmm_bundle_20260420
"""
from __future__ import annotations
import json
import numpy as np
from pathlib import Path
from scipy.optimize import minimize, differential_evolution

# ── Bundle path ───────────────────────────────────────────────────────────────
_HERE        = Path(__file__).parent
BUNDLE_DIR   = _HERE / "mmm_bundle_20260420"


# ── Load bundle ───────────────────────────────────────────────────────────────
with open(BUNDLE_DIR / "metadata.json") as _f:
    META = json.load(_f)

MEDIA_COLS           = META["media_cols"]
CONTROL_COLS         = META["control_cols"]
FEATURE_COLS         = META["feature_cols"]
MEDIA_LABELS         = META["media_labels"]
ADSTOCK              = META["adstock_params"]
HILL_ALPHA           = META["hill_alpha"]
HILL_K               = META["hill_k"]
SPEND_COL_MAP        = META["spend_col_map"]
_cal_raw             = META.get("calibration_factors", {})
CALIBRATION_FACTORS  = (
    {k: float(v) for k, v in _cal_raw["factors"].items()}
    if "factors" in _cal_raw and isinstance(_cal_raw["factors"], dict)
    else {k: float(v) for k, v in _cal_raw.items() if isinstance(v, (int, float))}
)
_iro_raw             = META.get("calibrated_iroas", {})
CALIBRATED_IROAS     = {k: float(v) for k, v in _iro_raw.items()}
GATE_DECISION        = META.get("gate_decision", "UNKNOWN")
CAUTION_FLAG         = META.get("caution_flag", False)
GATE_WARNINGS        = META.get("gate_warnings", [])

bm_bundle = np.load(BUNDLE_DIR / "beta_media_samples.npy")
bc_bundle = np.load(BUNDLE_DIR / "beta_ctrl_samples.npy")
ic_bundle = np.load(BUNDLE_DIR / "intercept_samples.npy")

_CTRL_DEFAULTS = np.array(META.get("ctrl_defaults", [0.0] * len(CONTROL_COLS)), dtype=float)


# ── Transformation helpers ─────────────────────────────────────────────────────
def _hill(x, alpha, K):
    if x <= 0:
        return 0.0
    xa, Ka = x ** alpha, K ** alpha
    return xa / (xa + Ka)


def transform_spend_vector(spend_dict):
    feats = []
    for hill_col, raw_col in SPEND_COL_MAP.items():
        s     = float(spend_dict.get(raw_col, 0.0))
        decay = ADSTOCK[raw_col]
        alpha = HILL_ALPHA[raw_col]
        K     = HILL_K[hill_col]
        x_ss  = s / (1.0 - decay)
        feats.append(_hill(x_ss, alpha, K))
    return np.array(feats, dtype=float)


def _default_controls():
    return _CTRL_DEFAULTS.copy()


# ── /predict ──────────────────────────────────────────────────────────────────
def predict_revenue(spend_dict, controls=None, ci_prob=0.94):
    x_media  = transform_spend_vector(spend_dict)
    x_ctrl   = controls if controls is not None else _default_controls()
    log_revs = ic_bundle + bm_bundle @ x_media + bc_bundle @ x_ctrl
    revs     = np.exp(log_revs)
    alpha    = (1.0 - ci_prob) / 2.0
    lo, hi   = np.quantile(revs, [alpha, 1 - alpha])
    total_sp = float(sum(spend_dict.values()))
    return dict(
        revenue_mean   =float(revs.mean()),
        revenue_median =float(np.median(revs)),
        revenue_ci_lo  =float(lo),
        revenue_ci_hi  =float(hi),
        ci_prob        =ci_prob,
        total_spend    =total_sp,
        roas_mean      =float(revs.mean() / max(total_sp, 1)),
        health_status  =GATE_DECISION,
        caution_flag   =CAUTION_FLAG,
        warnings       =GATE_WARNINGS,
    )


# ── /attribution ─────────────────────────────────────────────────────────────
def attribution(spend_dict, controls=None, calibration=None, calibrated_iroas=None):
    x_media  = transform_spend_vector(spend_dict)
    x_ctrl   = controls if controls is not None else _default_controls()
    cal      = calibration      if calibration      is not None else CALIBRATION_FACTORS
    cal_iro  = calibrated_iroas if calibrated_iroas is not None else CALIBRATED_IROAS
    media_t  = bm_bundle * x_media[np.newaxis, :]
    ctrl_t   = bc_bundle @ x_ctrl
    mu       = ic_bundle + media_t.sum(axis=1) + ctrl_t
    rev_mean = float(np.exp(mu).mean())
    channels = {}
    for i, col in enumerate(MEDIA_COLS):
        share      = float((media_t[:, i] / mu).mean())
        raw_col    = SPEND_COL_MAP[col]
        spend_usd  = float(spend_dict.get(raw_col, 0.0))
        rev_attr   = rev_mean * share
        roas_raw   = rev_attr / max(spend_usd, 1)
        cal_factor = float(cal.get(col, 1.0))
        roas_cal   = float(cal_iro.get(col, roas_raw))  # benchmark; fallback to raw
        channels[MEDIA_LABELS[col]] = dict(
            share_pct       =round(share * 100, 2),
            rev_attr_usd    =round(rev_attr, 2),
            spend_usd       =round(spend_usd, 2),
            roas_raw        =round(roas_raw, 3),
            roas_calibrated =round(roas_cal, 3),
            cal_factor      =round(cal_factor, 4),
        )
    return dict(
        baseline_share_pct =round(float((ic_bundle / mu).mean()) * 100, 2),
        controls_share_pct =round(float((ctrl_t / mu).mean()) * 100, 2),
        channels           =channels,
        total_spend        =float(sum(spend_dict.values())),
        health_status      =GATE_DECISION,
        caution_flag       =CAUTION_FLAG,
    )


# ── /optimize ────────────────────────────────────────────────────────────────
def optimize_budget(
    total_budget,
    controls=None,
    method="SLSQP",
    min_share=0.05,
    max_share=0.60,
    n_draws=200,
    hdi_prob=0.94,
    use_calibrated_iroas=True,
):
    if controls is None:
        controls = _default_controls()
    rng      = np.random.default_rng(0)
    idx      = rng.choice(bm_bundle.shape[0], size=min(n_draws, bm_bundle.shape[0]), replace=False)
    bm_o     = bm_bundle[idx]
    ic_o     = ic_bundle[idx]
    xc_o     = bc_bundle[idx] @ controls
    raw_cols = [SPEND_COL_MAP[c] for c in MEDIA_COLS]

    # When using raw iROAS, scale the posterior beta samples by the inverse
    # calibration factors so the optimiser sees uncalibrated returns.
    if use_calibrated_iroas:
        bm_eff = bm_o
    else:
        cal_factors = np.array(
            [float(CALIBRATION_FACTORS.get(c, 1.0)) for c in MEDIA_COLS], dtype=float
        )
        # cal_factor < 1 means raw >> calibrated; dividing by it reverses calibration
        bm_eff = bm_o / np.where(cal_factors > 0, cal_factors, 1.0)

    def neg_rev(alloc):
        x = transform_spend_vector(dict(zip(raw_cols, alloc)))
        return -np.exp(ic_o + bm_eff @ x + xc_o).mean()

    bounds     = [(min_share * total_budget, max_share * total_budget)] * len(MEDIA_COLS)
    slsqp_cons = [{"type": "eq", "fun": lambda a: a.sum() - total_budget}]
    x0         = np.full(len(MEDIA_COLS), total_budget / len(MEDIA_COLS))
    if method.upper() == "DE":
        from scipy.optimize import NonlinearConstraint
        de_cons = NonlinearConstraint(lambda a: a.sum(), total_budget, total_budget)
        res = differential_evolution(neg_rev, bounds, seed=42, constraints=de_cons)
    else:
        res = minimize(neg_rev, x0, method="SLSQP", bounds=bounds, constraints=slsqp_cons)

    opt = dict(zip(raw_cols, res.x))
    eq  = dict(zip(raw_cols, np.full(len(MEDIA_COLS), total_budget / len(MEDIA_COLS))))
    p_o = predict_revenue(opt, controls, hdi_prob)
    p_e = predict_revenue(eq,  controls, hdi_prob)

    rev_map   = {v: k for k, v in SPEND_COL_MAP.items()}
    alloc_out = {}
    for rc, s in opt.items():
        hc = rev_map[rc]
        alloc_out[MEDIA_LABELS[hc]] = dict(
            spend_usd=round(float(s), 2),
            share_pct=round(float(s) / total_budget * 100, 2),
        )
    return dict(
        total_budget           =total_budget,
        method                 =method,
        converged              =bool(res.success),
        optimal_allocation     =alloc_out,
        revenue_optimal_mean   =p_o["revenue_mean"],
        revenue_optimal_hdi_lo =p_o["revenue_ci_lo"],
        revenue_optimal_hdi_hi =p_o["revenue_ci_hi"],
        roas_optimal           =p_o["roas_mean"],
        revenue_equal_mean     =p_e["revenue_mean"],
        uplift_vs_equal_pct    =round(
            (p_o["revenue_mean"] - p_e["revenue_mean"]) / p_e["revenue_mean"] * 100, 2
        ),
        health_status          =GATE_DECISION,
        caution_flag           =CAUTION_FLAG,
    )


# ── /scenario ────────────────────────────────────────────────────────────────
def scenario(scenarios, controls=None, hdi_prob=0.94):
    results = []
    for sc in scenarios:
        name = sc.get("name", "unnamed")
        sp   = {k: sc.get(k, 0.0) for k in ["spend_ps", "spend_pmax", "spend_fb", "spend_ig"]}
        p    = predict_revenue(sp, controls, hdi_prob)
        results.append(dict(
            name         =name,
            spend        =sp,
            total_spend  =p["total_spend"],
            revenue_mean =p["revenue_mean"],
            revenue_ci_lo=p["revenue_ci_lo"],
            revenue_ci_hi=p["revenue_ci_hi"],
            roas_mean    =p["roas_mean"],
        ))
    return results
